name: MCP Server
version: "1.1.0"
slug: mcp_server
description: Minimal Python addon for Home Assistant
startup: application
boot: auto
arch:
  - amd64
  - aarch64
ingress: false
host_network: true
options: {}
schema: {}
