name: MCP Server
version: "2.1.0"
slug: mcp_server
description: Python addon with Dockerfile
startup: services
boot: auto
init: false
arch:
  - amd64
  - aarch64
ingress: false
host_network: true
options: {}
schema: {}
